[package]
name = "pacmog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "1.0", default-features = false }
fixed = "1.20.0"
nom = "7.1.1"

[dev-dependencies]
cpal = "0.14.1"
approx = "0.5.1"
criterion = "0.4"

[[bench]]
name = "bench"
harness = false
