[package]
name = "pacmog"
version = "0.5.0"
authors = ["Akiyuki Okayasu <akiyuki.okayasu@gmail.com>"]
description = "PCM decording library"
categories = ["multimedia::audio", "no-std", "embedded", "multimedia::encoding"]
keywords = ["audio", "wav"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/pacmog"
readme = "README.md"
edition = "2021"
rust-version = "1.79.0"

[dependencies]
arbitrary-int = { version = "1.2.7", default-features = false }
fixed = "1.23.1"
heapless = "0.8.0"
nom = { version = "7.1.3", default-features = false }
embedded-error-chain = "1.0.0"

[dev-dependencies]
cpal = "0.15.2"
approx = "0.5.1"
criterion = "0.4.0"

[[bench]]
name = "bench"
harness = false
