[package]
name = "pacmog"
version = "0.3.1"
authors = ["Akiyuki Okayasu <akiyuki.okayasu@gmail.com>"]
description = "PCM decording library"
categories = ["multimedia::audio", "no-std", "embedded", "multimedia::encoding"]
keywords = ["audio", "wav"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/pacmog"
readme = "README.md"
edition = "2021"
rust-version = "1.66"

[dependencies]
anyhow = {version = "1.0", default-features = false }
fixed = "1.20.0"
heapless = "0.7.16"
nom = {version = "7.1.2", default-features = false }

[dev-dependencies]
cpal = "0.14.2"
approx = "0.5.1"
criterion = "0.4"

[[bench]]
name = "bench"
harness = false
