[package]
name = "pacmo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"

[dev-dependencies]
cpal = "0.14.0"
approx = "0.5.1"