[package]
name = "pacmog"
version = "0.1.0"
authors = ["Akiyuki Okayasu <akiyuki.okayasu@gmail.com>"]
description = "PCM parser"
categories = ["audio", "no-std"]
keywords = ["audio", "wav"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/AkiyukiOkayasu/pacmog"
readme = "README.md"
edition = "2021"
rust-version = "1.65"

[dependencies]
anyhow = {version = "1.0", default-features = false }
fixed = "1.20.0"
nom = "7.1.1"

[dev-dependencies]
cpal = "0.14.2"
approx = "0.5.1"
criterion = "0.4"

[[bench]]
name = "bench"
harness = false
