name: CI

on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: install libasound2-dev
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add rustfmt && rustup component add clippy
      - name: Print Rust version
        run: rustc --version
      - name: Formatter
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test --verbose
      - name: Run examples
        run: |
          cargo build --example beep
          cargo build --example beep_imaadpcm
          cargo build --example beep_imaadpcm_stereo
          cargo build --example print_sample_values
          cargo build --example read_wav_no_std
          cargo build --example read_ima_adpcm_no_std
